name: "*nix Build"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

env:
  SOURCE_DIR: ${{ github.workspace }}
  QT_VERSION: 6.7.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            qt_host: mac
            qt_arch: clang_64
          - os: ubuntu-20.04
            qt_host: linux
            qt_arch: linux_gcc_64
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: ${{ matrix.qt_host }}
          target: desktop
          arch: ${{ matrix.qt_arch }}
          modules: "qtpositioning qtwebchannel qtwebengine qtwebview qt5compat"
          cache: true
          cache-key-prefix: qtcache
          setup-python: true
          tools: "tools_qtcreator,qt.tools.qtcreator tools_qtcreator_gui,qt.tools.qtcreator_gui tools_ifw"

      - name: Configure
        run: |
          qmake qcDashboard.pro

      - name: Build
        run: |
          make -j4

      - name: Deploy (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          macdeployqt qcDashboard.app -qmldir=. -verbose=1

      - name: Extract linuxdeployqt
        if: matrix.os == 'ubuntu-20.04'
        run: |
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          ./linuxdeployqt-continuous-x86_64.AppImage --appimage-extract
          sudo mv squashfs-root /usr/local/linuxdeployqt

      - name: Deploy (Linux)
        if: matrix.os == 'ubuntu-20.04'
        run: |
          /usr/local/linuxdeployqt/AppRun qcDashboard -qmldir=${{ env.SOURCE_DIR }} -verbose=1 -plugin=qt5compat

      - name: Package Artifact (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          tar czf qcDashboard-${{ matrix.os }}.tar.gz qcDashboard.app

      - name: Package Artifact (Linux)
        if: matrix.os == 'ubuntu-20.04'
        run: |
          tar czf qcDashboard-${{ matrix.os }}.tar.gz qcDashboard

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: qcDashboard-${{ matrix.os }}
          path: qcDashboard-${{ matrix.os }}.*
